# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vichar Sharma
title: Senior DevOps Engineer
email: v4.charusharma@hotmail.com
website: www.github.com/vicharsharma

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: v4sharma
github_username:  vicharsharma
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: v4sharma
linkedin_username: vicharsharma
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: vicharsharma
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: VicharSharma
  icon: fas fa-globe
  url: https://vicharsharma.github.io/myData/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Vichar and I'm a senior DevOps Engineer. As well as DevOps systems I also have experience in automation testing. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: 
        link: 
        # link_text: Project Website
        additional_links:
          - title:  
            icon: 
            url: 
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <mark>AWS</mark>      <mark>Terraform</mark>      <mark>Jenkins</mark>      <mark>git</mark>      <mark>CI/CD</mark>
          
          <mark>Python</mark>     <mark>Shell Scripting</mark>     <mark>Groovy</mark>      <mark>Kubernetes</mark>     <mark>Docker Containerisation</mark> 
          
          <mark>VM</mark>     <mark>Oracle Virtual box</mark>      <mark>Agile</mark>      <mark>Scrum</mark>  

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microfocus(ex HPE)
        link: https://www.microfocus.com/en-us/home
        link_text: www.microfocus.com
        sub_title: DevOps Engineer
        caption: July 2019 - Jan 21
        quote: >
          Solving the build and Deployment problems as being that *DevOps Guy*.
        description: | # this will include new lines to allow paragraphs
          ▪ Managed 300 plus Jenkins jobs for a product with nightly runs.
          
          ▪ Created awesome dashboard to see the status of all Jenkins jobs on one page.
          
          ▪ Configured Sonar code coverage for java ,go repos.
          
          ▪ STAT scan configuration.
          
          ▪ Dockerized builds and Jenkinfile optimization.
          
          ▪ CI-CD implementation , with git, build job with every commit and pull requests builds,webhooks.
          
          ▪ Wrote pipeline scripts in groovy.
          
          ▪ Jenkins administration and complete ownership for DevOps for two products R&D teams.
          
          ▪ Worked on migration from Electric commander to Jenkins in order to save license cost.
          
          ▪ Build jobs using Kubernetes pods.
          

      - layout: left
        title: Visteon (from Wipro)
        link: https://www.visteon.com/
        link_text: www.visteon.com
        sub_title: Test Engineer
        caption: Dec 2018 - Jul 2019
        quote: >
          Development of software for Visteon Self driving module Drivecore.
        description: | # this will include new lines to allow paragraphs
          ▪ Test case designing for the ADAS features.
          
          ▪ Test Scenarios creation using IPG carmaker tool / Vires VTD tool on Linux.
          
          ▪ Test execution for ADAS features like LKA,LDW,ACC,BSD.
          
          
      - layout: left
        title: HP LIP(from Wipro)
        link: https://developers.hp.com/hp-linux-imaging-and-printing
        link_text: HP Linux Imaging and Printing
        sub_title: Test Engineer
        caption: Jul 2016 - Nov 2018
        quote: >
          To deliver the Printer Driver for HP printers on <mark>Linux Platform</mark> which includes end to end development and Testing of the Driver.
        description: | # this will include new lines to allow paragraphs
          ▪ Test Automation using Python.
          
          ▪ Responsible for All of the testing Activities for the project.
          
          ▪ Direct working with client and understanding the requirements.
          
          ▪ Test Planning for the Release, Designing TCs and Preparing Test Suite.
          
          ▪ Basic Smoke testing, Component Testing, Functionality Testing, Performance testing, Regression Testing and User Acceptance Testing (UAT).
          
          ▪ Bug monitoring and Test results management in ALM (Application lifecycle management).
 
      - layout: left
        title: HP UPD(from Wipro)
        link: https://www8.hp.com/us/en/solutions/business-solutions/printingsolutions/upd.html
        link_text: HP Universal Print Driver
        sub_title: Test Engineer
        caption: Aug 2015 - Jun 2016
        quote: >
          To deliver the Printer Driver for HP printers on <mark>Windows Platform</mark> which includes end to end development and Testing of the Driver.
        description: | # this will include new lines to allow paragraphs
          ▪ Automation Tool Framework (ATF) script Preparation and running (QTP).
          
          ▪ Testing in Citrix Cluster environment. WHQL (Windows Hardware Quality Labs) testing.
          
          ▪ CR(Change Request)/Bug logging and Test result management in ALM(Application lifecycle management)
 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Rajasthan Technical University
        caption: 2011 - 2015
        sub_title: Electronics Instrumentation and Control Engineering
        quote: >
          RTU was established in 2006 by the Government of Rajasthan to enhance the technical education in the state, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in India.
        description: | # this will include new lines to allow paragraphs
          During my time at RTU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
